version: "3"
services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-rest-api
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - /db_data:/data/db
    ports:
      - 27016:27017
networks:
  mongo-app:
    driver: bridge